env:
    CIRRUS_CLONE_DEPTH: 1
   
task:
    name: aosp build
    timeout_in: 120m 
    container:
      image: apon77/aosp:latest
      cpu: 8
      memory: 32G
    build_script:
      - df -h
      - chmod +x build.sh
      - ./build.sh
