env:
    CIRRUS_CLONE_DEPTH: 1
   
task:
    name: build kernel
    timeout_in: 120m 
    container:
      image: x0rzavi/gentoo-kernel:latest
      cpu: 8
      memory: 32G
    build_script:
      - source ./build.sh
      - source ./upload.sh
