env:
    CIRRUS_CLONE_DEPTH: 1
   
task:
    name: aosp build
    timeout_in: 120m 
    container:
      image: apon77/aosp:latest
      cpu: 12
      memory: 24G
    build_script:
      - chmod +x build.sh
      - ./build.sh
