---
kind: pipeline
type: docker
name: test

platform:
  os: linux
  arch: amd64

steps:
- name: check
  image: archlinux:latest
  commands:
  - pacman -Syu --noconfirm --needed
  - pacman -S neofetch --noconfirm
  - neofetch
  - df -h
  - free -h
  - pwd
  - lsblk
