---
kind: pipeline
type: docker
name: test

platform:
  os: linux
  arch: arm64

steps:
- name: check
  image: ubuntu:rolling
  commands:
  - apt update
  - apt install neofetch -y
  - neofetch
  - df -h
  - free -h
  - pwd
  - lsblk
