---
kind: pipeline
type: docker
name: build kernel

steps:
- name: build
  image: x0rzavi/gentoo-kernel:latest
  environment: 
    NGROK_AUTH_TOKEN:
      from_secret: NGROK_AUTH_TOKEN
  commands:
    - source ./test_script.sh
