---
kind: pipeline
type: docker
name: build kernel

platform:
  os: linux
  arch: amd64

steps:
- name: check
  image: mcr.microsoft.com/vscode/devcontainers/universal:linux
  commands:
    - docker info
