version: "3"
services:
  navidrome:
    image: deluan/navidrome:latest
    user: 1001:121 # should be owner of volumes
    ports:
      - "4533:4533"
    restart: unless-stopped
    environment:
      # Optional: put your config options customization here. Examples:
      ND_SCANSCHEDULE: 1h
      ND_LOGLEVEL: info  
      ND_SESSIONTIMEOUT: 24h
      ND_BASEURL: ""
    volumes:
      - "/home/runner/work/ci-circus/ci-circus/data:/data"
      - "/home/runner/work/ci-circus/ci-circus/music:/music:ro"
