version: 2.1

workflows:
  main:
    jobs:
      - tmate

jobs:
  tmate:
    docker:
      - image: ubuntu
    steps:
      - run: apt update
      - run: curl https://www.teleconsole.com/get.sh | sh
      - run: teleconsole
