version: 2.1

workflows:
  main:
    jobs:
      - tmate

jobs:
  tmate:
    docker:
      - image: ubuntu
    steps:
      - run: apt update
      - run: apt install curl sudo wget git tmate -y
      - run: tmate -F
