name: CI
on:
  push:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: gentoo/stage3:latest
    steps:
      - uses: actions/checkout@master
      - name: script
        run: bash script.sh
