name: Test
on:
  push:
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    container:
      image: ubuntu:latest
    steps:
      - uses: actions/checkout@master
      - name: test
        run: |
          cat /etc/ssh/sshd_config
          systemctl start sshd
          systemctl status sshd
