name: CI
on:
  push:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: gentoo/stage3:latest
    steps:
      - uses: actions/checkout@master
      - name: script
        id: kerneltag
        run: |
          echo "tag"
      - name: test
        run: |
          echo ${{ steps.kerneltag.outputs }}
    env:
        NGROK_AUTH_TOKEN: ${{ secrets.NGROK_AUTH_TOKEN }}
