name: CI
on:
  push:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: gentoo/stage3:latest
    steps:
      - uses: actions/checkout@master
      - name: script
        run: |
          echo "hi" > tag
      - name: test
        run: |
          export TAG="$(cat tag)"
          echo $TAG
      - name: Release
        uses: softprops/action-gh-release@master
        with:
          files: tag
          tag_name: $TAG
    env:
        NGROK_AUTH_TOKEN: ${{ secrets.NGROK_AUTH_TOKEN }}
